# Main Travis CI configuration file for wordpress-plugin tests
# https://github.com/benbalter/wordpress-plugin-tests

# Tell Travis CI we're using PHP
language: php

# Versions of PHP to test against
php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5

# Specify versions of WordPress to test against
# WP_VERSION = WordPress version number (use "master" for SVN trunk)
# WP_MULTISITE = whether to test multisite (use either "0" or "1")
env:
    - WP_VERSION=master WP_MULTISITE=0
    - WP_VERSION=3.5.2 WP_MULTISITE=0
    - WP_VERSION=3.6.1 WP_MULTISITE=0
    - WP_VERSION=master WP_MULTISITE=1
    - WP_VERSION=3.5.2 WP_MULTISITE=1
    - WP_VERSION=3.6.1 WP_MULTISITE=1

# Grab the setup script and execute
before_script:
    - export WP_TESTS_DIR=/tmp/wordpress-tests/
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 

after_script:
    - phpenv local 5.4
    - php vendor/bin/coveralls -v
    - phpenv local --unset

script: phpunit --coverage-clover clover.xml
